// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY1pzLT7vwbqYIhOjQHlc-v6we1y38fQE',
    appId: '1:455000053940:web:0f0a8434082e181bd69fe1',
    messagingSenderId: '455000053940',
    projectId: 'project-hydrolink',
    authDomain: 'project-hydrolink.firebaseapp.com',
    storageBucket: 'project-hydrolink.appspot.com',
    measurementId: 'G-S7HFDVQH48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiQzjHJiYvMLLqLygklWhJUqKqa4MBRYw',
    appId: '1:455000053940:android:cf57831bb59f9668d69fe1',
    messagingSenderId: '455000053940',
    projectId: 'project-hydrolink',
    storageBucket: 'project-hydrolink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfPdbg8ZDu419OQvPQoAq4UG2mPBk-Hig',
    appId: '1:455000053940:ios:233b0a0d2ce07eb8d69fe1',
    messagingSenderId: '455000053940',
    projectId: 'project-hydrolink',
    storageBucket: 'project-hydrolink.appspot.com',
    iosClientId:
        '455000053940-grtmenh14rsot1delu6t9rghf26n6kqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrolink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfPdbg8ZDu419OQvPQoAq4UG2mPBk-Hig',
    appId: '1:455000053940:ios:233b0a0d2ce07eb8d69fe1',
    messagingSenderId: '455000053940',
    projectId: 'project-hydrolink',
    storageBucket: 'project-hydrolink.appspot.com',
    iosClientId:
        '455000053940-grtmenh14rsot1delu6t9rghf26n6kqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrolink',
  );
}
