// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0mRvj-eTjI0ysWuabEKSay0sOVlQhYmg',
    appId: '1:207507465271:web:504d291c2999ee55908bb2',
    messagingSenderId: '207507465271',
    projectId: 'project-hydrolink-c1716',
    authDomain: 'project-hydrolink-c1716.firebaseapp.com',
    storageBucket: 'project-hydrolink-c1716.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlTe69jd1af5sP800iNRIQNNbzgxbpPg',
    appId: '1:207507465271:android:7dae804c17e483a7908bb2',
    messagingSenderId: '207507465271',
    projectId: 'project-hydrolink-c1716',
    storageBucket: 'project-hydrolink-c1716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4cPLOD9xv0ulrhr-BmY5L_9ilG3mcpoA',
    appId: '1:207507465271:ios:772c12bd14532101908bb2',
    messagingSenderId: '207507465271',
    projectId: 'project-hydrolink-c1716',
    storageBucket: 'project-hydrolink-c1716.appspot.com',
    iosClientId: '207507465271-5ed7ufpd44lqqndoueq0b8pt2vkc1tbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrolink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4cPLOD9xv0ulrhr-BmY5L_9ilG3mcpoA',
    appId: '1:207507465271:ios:772c12bd14532101908bb2',
    messagingSenderId: '207507465271',
    projectId: 'project-hydrolink-c1716',
    storageBucket: 'project-hydrolink-c1716.appspot.com',
    iosClientId: '207507465271-5ed7ufpd44lqqndoueq0b8pt2vkc1tbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrolink',
  );
}
